services:
  app:
    container_name: events
    image: tomjtoth/events
    build:
      context: .
      tags:
        - tomjtoth/events
    restart: unless-stopped
    volumes:
      - ./data:/app/data
